---
# tasks file for ansible-role-bdii
#
 - name: setup UMD4 repos
   template: src=umd4.repo.j2 dest=/etc/yum.repos.d/umd.repo mode=0644
   when: ansible_os_family == "RedHat" and umd_repo_file

 - name: install umd4-release rpm
   yum: name={{ umd_rpm }} state=installed
   when: ansible_os_family == "RedHat" and umd_repo_rpm

 - name: install site_bdii packages
   action: >
     {{ ansible_pkg_mgr }}
     name="{{ item }}"
     state=installed
   with_items: site_bdii_packages
   when: site_bdii_enabled

 - name: add site-urls
   lineinfile:
     dest="/etc/bdii/gip/site-urls.conf"
     regexp='{{ item.regexp }}'
     line='{{ item.line }}'
     create=yes
     backup=yes
     owner={{ site_bdii_user }}
   with_items: site_bdii_site_urls
   notify:
    - restart bdii

 - name: add glite-info-site-defaults
   lineinfile:
     dest="/etc/bdii/gip/glite-info-site-defaults.conf"
     regexp='{{ item.regexp }}'
     line='{{ item.line }}'
     create=yes
     backup=yes
     owner={{ site_bdii_user }}
   with_items: site_bdii_glite_info_site_defaults
   notify:
    - restart bdii

 - name: enable and start bdii service
   service: name=bdii enabled=yes state=started
