---
# tasks file for ansible-role-bdii
#
 - name: setup UMD4 repos
   template: src=umd4.repo.j2 dest=/etc/yum.repos.d/umd.repo mode=0644
   when: ansible_os_family == "RedHat" and umd_repo_file

 - name: install umd4-release rpm
   yum: name={{ umd_rpm }} state=installed
   when: ansible_os_family == "RedHat" and umd_repo_rpm

 - name: install site_bdii packages
   action: >
     {{ ansible_pkg_mgr }}
     name="{{ item }}"
     state=installed
   with_items: site_bdii_packages
   when: site_bdii_enabled

 - name: template in config files
   template: src=files/{{ item }} dest=/etc/bdii/gip/ mode=0640 backup=yes
   register: reg-site_bdii_site_info
   when: site_bdii_enabled and site_bdii_files.0 != ""
   with_items: site_bdii_files
   notify:
    - restart bdii

# TODO: howto run /opt/glite/yaim/bin/yaim -c -s site-info.def -n BDII_site on EL7?
# - name: run yaim
#   command: 
#   when: reg-site_bdii_site_info.changed
